#![allow(dead_code)]

use baozi_core::{BaoziError, Diagnostic, Result, Scene};
use baozi_format_ply::PlyImporter;
use baozi_import::{FormatImporter, ImportContext, ImportOptions};
use baozi_io::{AssetPath, MemoryAssetIo};
use std::sync::Arc;

pub fn import_bytes(source: &str, bytes: &[u8]) -> Result<(Scene, Vec<Diagnostic>)> {
    let (scene, diagnostics) = import_bytes_result(source, bytes, ImportOptions::memory())?;
    Ok((scene?, diagnostics))
}

pub fn import_bytes_result(
    source: &str,
    bytes: &[u8],
    options: ImportOptions,
) -> Result<(Result<Scene>, Vec<Diagnostic>)> {
    let path = AssetPath::new(source)?;
    let mut io = MemoryAssetIo::new();
    io.insert(path.clone(), Arc::<[u8]>::from(bytes));
    let mut ctx = ImportContext::with_options(&io, path, options);
    let result = PlyImporter.read(&mut ctx);
    let diagnostics = ctx.into_diagnostics();
    Ok((result, diagnostics))
}

pub fn expected_error(result: Result<Scene>) -> Result<BaoziError> {
    match result {
        Ok(_) => Err(BaoziError::parse(
            "test",
            None,
            "expected PLY import to fail",
        )),
        Err(error) => Ok(error),
    }
}

pub fn ascii_triangle() -> &'static [u8] {
    b"ply
format ascii 1.0
comment fixture triangle
obj_info generated by baozi tests
element vertex 3
property float x
property float y
property float z
property float nx
property float ny
property float nz
property float s
property float t
property uchar red
property uchar green
property uchar blue
property float temperature
element face 1
property list uchar uint vertex_indices
end_header
0 0 0 0 0 1 0 0 255 0 0 0.5
1 0 0 0 0 1 1 0 0 255 0 0.75
0 1 0 0 0 1 0 1 0 0 255 1.0
3 0 1 2
"
}

pub fn ascii_point_cloud() -> &'static [u8] {
    b"ply
format ascii 1.0
element vertex 2
property float x
property float y
property float z
end_header
0 0 0
1 2 3
"
}

pub fn ascii_quad() -> &'static [u8] {
    b"ply
format ascii 1.0
element vertex 4
property float x
property float y
property float z
element face 1
property list uchar uint vertex_indices
end_header
0 0 0
1 0 0
1 1 0
0 1 0
4 0 1 2 3
"
}

pub fn binary_triangle(little_endian: bool) -> Vec<u8> {
    let format = if little_endian {
        "binary_little_endian"
    } else {
        "binary_big_endian"
    };
    let mut bytes = format!(
        "ply\nformat {format} 1.0\nelement vertex 3\nproperty float x\nproperty float y\nproperty float z\nelement face 1\nproperty list uchar uint vertex_indices\nend_header\n"
    )
    .into_bytes();
    for position in [[0.0f32, 0.0, 0.0], [1.0f32, 0.0, 0.0], [0.0f32, 1.0, 0.0]] {
        for value in position {
            if little_endian {
                bytes.extend_from_slice(&value.to_le_bytes());
            } else {
                bytes.extend_from_slice(&value.to_be_bytes());
            }
        }
    }
    bytes.push(3);
    for index in [0u32, 1, 2] {
        if little_endian {
            bytes.extend_from_slice(&index.to_le_bytes());
        } else {
            bytes.extend_from_slice(&index.to_be_bytes());
        }
    }
    bytes
}
